import type { NextPage,GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import {LinkCardWithArea} from '@/component/app/LinkCardWithArea';
import type {AreaGraphProps} from '@/component/app/LinkCardWithArea';
import {LinkCardWithPie} from '@/component/app/LinkCardWithPie';
import type {PieGraphProps} from '@/component/app/LinkCardWithPie';
import { Grid, Text, Spacer,} from '@nextui-org/react';


// Homeページへの引数
type HomeStaticProps = {
  dummy:string;
}


//*** 本日の検査数の推移を表すグラフコンポーネント ***//
const CurerntTests = () =>{
  const areaGraphProps:AreaGraphProps = {
    dummy: "sss",
    data : [
      {
        time: '8:00',
        value1: 10,
        value2: 3,
      },
      {
        time: '9:00',
        value1: 210,
        value2: 128,
      },
      {
        time: '10:00',
        value1: 527,
        value2: 231,
      },
      {
        time: '11:00',
        value1: 770,
        value2: 345,
      },
      {
        time: '12:00',
        value1: 690,
        value2: 454,
      },
      {
        time: '13:00',
        value1: 200,
        value2: 123,
      },
      {
        time: '14:00',
        value1: 150,
        value2: 74,
      },
    ],
  }
  return(
      <LinkCardWithArea url="https://nextjs.org/docs" title="現在の総検査数" 
      areaGraphProps={areaGraphProps}
      footerText="クリックすると詳細情報を確認できます"
      />
  )
}


//*** 本日のエラー数の推移を表すグラフコンポーネント ***//

const CurerntError = () =>{
  const areaGraphProps:AreaGraphProps = {
    dummy: "sss",
    data : [
      {
        time: '8:00',
        value1: 1,
        value2: 3,
      },
      {
        time: '9:00',
        value1: 2,
        value2: 1,
      },
      {
        time: '10:00',
        value1: 5,
        value2: 2,
      },
      {
        time: '11:00',
        value1: 7,
        value2: 3,
      },
      {
        time: '12:00',
        value1: 6,
        value2: 4,
      },
      {
        time: '13:00',
        value1: 2,
        value2: 1,
      },
      {
        time: '14:00',
        value1: 10,
        value2: 7,
      },
    ],
  }
  return(
      <LinkCardWithArea  url="https://nextjs.org/docs" title="現在の総エラー数" 
      areaGraphProps={areaGraphProps}
      footerText="クリックすると詳細情報を確認できます"
      />
  )
}


//*** 検査数の多い施設名を表すグラフコンポーネント ***//
const BigUser = () =>{
  const pieGraphProps:PieGraphProps = {
   
    data : [
      {
        name: '大阪病院',
        value: 112342,
      },
      {
        name: '東京病院',
        value: 122999,
      },
      {
        name: '北海道病院',
        value: 122435,
      },
      {
        name: '愛知病院',
        value: 133313,
      },
      {
        name: '福岡病院',
        value: 23431,
      },
      
    ],
    pieType:"donuts"
  }
  return(
      <LinkCardWithPie   url="https://nextjs.org/docs" title="ビッグユーザー Top 5" 
      pieGraphProps={pieGraphProps}
      footerText="クリックすると詳細情報を確認できます"
      />
  )
}



//*** 消費量の多い試薬を表すグラフコンポーネント ***//
const  TypicalAnalytes= () =>{
  const pieGraphProps:PieGraphProps = {
   
    data : [
      {
        name: 'AFP',
        value: 2123,
      },
      {
        name: 'CEA',
        value: 2399,
      },
      {
        name: 'HBsAg',
        value: 4456,
      },
      {
        name: 'HBsAb',
        value: 4562,
      },
      {
        name: 'Cov19',
        value: 3245,
      },
      
    ],
    pieType:"pie"
  }
  return(
      <LinkCardWithPie   url="https://nextjs.org/docs" title="検査試薬 Top 5" 
      pieGraphProps={pieGraphProps}
      footerText="クリックすると詳細情報を確認できます"
      />
  )
}


const Home: NextPage<HomeStaticProps> = (props) => {
  

   return (
    <div className={styles.container}>
      <Head>
        <title>NextUI | Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Text size={60} h1 b css={{ textGradient: "180deg, $purple500 20%, $pink500 100%" }}>
          Welcome to IoT system !
        </Text>

        
      <Grid.Container
        gap={2}
        justify="center"
        alignItems="center"
        css={{ maxW:2000, marginTop:50 }}
      >
        <Grid xs={12} md={6} justify="center">
          <CurerntTests/>
        </Grid>
        <Grid xs={12} md={6}  justify="center">
          <CurerntError/>
        </Grid>
        
        <Grid xs={12} md={6} justify="center">
          <BigUser/>
        </Grid>

        <Grid xs={12} md={6} justify="center">
          <TypicalAnalytes/>
        </Grid>


        <Spacer y={1}/>
        <Grid xs={12} md={12} justify="center">

          <iframe src='https://webchat.botframework.com/embed/dotnetbot-bot?s=FaRy1tSDNy0.WpPB4f5c0u0RsvQa-2H9RIfAF0DeUa3SJcl1uCYB89M' 
          width="1000" height="450" ></iframe>
        </Grid>

      </Grid.Container>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


export const getStaticProps: GetStaticProps<HomeStaticProps> = async () => {
  console.log("Home SSG running !!!\n");
  return {
    props: {
      dummy: "dummy",
    },
    // revalidate: 1,
  };
}


export default Home;
